---
# tasks file for roles/configure_webservers

- name: Installation de nginx et php
  apt:
    name: ['nginx','php-fpm']
    state: latest



# - name: Copie des fichiers web
#   file:
#     src: index.html
#     dest: /var/www/index.html
#     mode: preserve
#     state: present
#   notify: restart_nginx


- name: Application du template de configuration nginx
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart_nginx

- name: Activation du nouveau site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart Nginx

- meta : flush_handlers






- meta : flush_handlers















